import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    FIREBASE_ADMIN_SERVICE_ACCOUNT_BASE64: !!process.env.FIREBASE_ADMIN_SERVICE_ACCOUNT_BASE64,
    FIREBASE_ADMIN_PROJECT_ID: !!process.env.FIREBASE_ADMIN_PROJECT_ID,
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: !!process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    FIREBASE_ADMIN_CLIENT_EMAIL: !!process.env.FIREBASE_ADMIN_CLIENT_EMAIL,
    FIREBASE_ADMIN_PRIVATE_KEY: !!process.env.FIREBASE_ADMIN_PRIVATE_KEY,
    FIREBASE_ADMIN_PRIVATE_KEY_LENGTH: process.env.FIREBASE_ADMIN_PRIVATE_KEY?.length ?? 0,
    FIREBASE_ADMIN_PRIVATE_KEY_STARTS: process.env.FIREBASE_ADMIN_PRIVATE_KEY?.slice(0, 30) ?? null,
  });
}
